### ISSUE TITLE
Proposal: version numbers

### ISSUE THREAD

**Issue by eric-schleicher** [EX0l0N/ply-to-SculptrVR-csv#2]
If new versions break functionality, it would be handy to keep a few versions around that are known good for various purposed.  I move machine and found myself in a spot where i couldn't get to the older version.

It would be nice if the releases tab would list them too.

:)

**Comment by EX0l0N** [comment]
Yes, you're right. I've been thinking about using version numbers all the time, but I always thought, this thing is to small for that.
And then somehow I missed the point where I should have started using them. Let's see if I can tag some good spots.

**Comment by EX0l0N** [comment]
Most likely this is the version you were looking for: [v0.2 binaries](https://github.com/EX0l0N/ply-to-SculptrVR-csv/tree/v0.2/bin)
